# Generated by Django 4.2.7 on 2023-12-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlaughterhouseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(choices=[('goats', 'Goats'), ('sheep', 'Sheep'), ('cows', 'Cows'), ('pigs', 'Pigs')], default='goats', max_length=255)),
                ('slaughter_date', models.DateField(auto_now_add=True)),
                ('part_name', models.CharField(choices=[('ribs', 'Ribs'), ('thighs', 'Thighs'), ('loin', 'Loin'), ('shoulder', 'Shoulder'), ('shanks', 'Shanks'), ('organ_meat', 'Organ Meat'), ('intestines', 'Intestines'), ('tripe', 'Tripe'), ('sweetbreads', 'Sweetbreads')], default='shanks', max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('slaughtered', 'Slaughtered'), ('in_the warehouse', 'In The Warehouse'), ('sold', 'Sold')], default='slaughtered', max_length=255)),
                ('sale_choice', models.CharField(choices=[('export_cuts', 'Export Cuts'), ('local_sale_cuts', 'Local Sale Cuts')], default='export_cuts', max_length=255)),
            ],
        ),
    ]
