# Generated by Django 4.2.7 on 2023-12-07 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaughterhouseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slaughter_date', models.DateField(auto_now_add=True)),
                ('part_name', models.CharField(choices=[('thighs', 'Thighs'), ('ribs', 'Ribs'), ('loin', 'Loin'), ('shoulder', 'Shoulder'), ('shanks', 'Shanks'), ('organ_meat', 'Organ Meat'), ('intestines', 'Intestines'), ('tripe', 'Tripe'), ('sweetbreads', 'Sweetbreads')], default='shank', max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.inventorybreed')),
            ],
        ),
    ]
