# Generated by Django 4.2.7 on 2023-12-07 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_breadertrade_total_quantity_supplied'),
        ('slaughter_house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaughterhouserecord',
            name='created_by',
        ),
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='breed',
            field=models.CharField(choices=[('goats', 'Goats'), ('sheep', 'Sheep'), ('cows', 'Cows'), ('pigs', 'Pigs')], default='goats', max_length=255),
        ),
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='inventory_breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.breadertrade'),
        ),
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='part_name',
            field=models.CharField(choices=[('ribs', 'Ribs'), ('thighs', 'Thighs'), ('loin', 'Loin'), ('shoulder', 'Shoulder'), ('shanks', 'Shanks'), ('organ_meat', 'Organ Meat'), ('intestines', 'Intestines'), ('tripe', 'Tripe'), ('sweetbreads', 'Sweetbreads')], default='shanks', max_length=255),
        ),
    ]
