# Generated by Django 5.0.1 on 2024-02-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='breed',
            field=models.CharField(blank=True, default='goats', max_length=255, null=True),
        ),
    ]
