# Generated by Django 4.2.7 on 2023-12-09 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaughterhouserecord',
            name='part_name',
        ),
    ]
