# Generated by Django 5.0.1 on 2024-02-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0002_alter_slaughterhouserecord_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
