# Generated by Django 4.2.7 on 2023-12-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0002_remove_slaughterhouserecord_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaughterhouserecord',
            name='part_name',
        ),
    ]
