# Generated by Django 4.2.7 on 2023-12-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0002_remove_slaughterhouserecord_part_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaughterhouserecord',
            name='sale_choice',
        ),
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='status',
            field=models.CharField(choices=[('slaughtered', 'Slaughtered')], default='slaughtered', max_length=255),
        ),
    ]
