# Generated by Django 4.2.7 on 2023-12-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0003_remove_slaughterhouserecord_part_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='part_name',
            field=models.CharField(choices=[('ribs', 'Ribs'), ('thighs', 'Thighs'), ('loin', 'Loin'), ('shoulder', 'Shoulder'), ('shanks', 'Shanks'), ('organ_meat', 'Organ Meat'), ('intestines', 'Intestines'), ('tripe', 'Tripe'), ('sweetbreads', 'Sweetbreads')], default='shanks', max_length=255),
        ),
    ]
