# Generated by Django 5.0.1 on 2024-03-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0003_slaughterhouserecord_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
