# Generated by Django 5.0.1 on 2024-03-05 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_controlcenter_seller'),
        ('slaughter_house', '0003_slaughterhouserecord_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='control_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.controlcenter'),
        ),
    ]
