# Generated by Django 4.2.7 on 2023-12-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0040_alter_breedcut_quantity_left'),
        ('slaughter_house', '0003_remove_slaughterhouserecord_associated_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='associated_sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.inventorybreedsales'),
        ),
    ]
