# Generated by Django 5.0.1 on 2024-03-04 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_remove_controlcenter_total_breed_supply_non_negative_and_more'),
        ('slaughter_house', '0004_slaughterhouserecord_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='control_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.controlcenter'),
        ),
    ]
