# Generated by Django 4.2.7 on 2023-12-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0005_remove_slaughterhouserecord_inventory_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='sale_type',
            field=models.CharField(choices=[('in_the warehouse', 'In The Warehouse'), ('slaughtered', 'Slaughtered'), ('sold', 'Sold')], default='in_warehouse', max_length=255),
        ),
    ]
