# Generated by Django 4.2.7 on 2023-12-06 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0040_alter_breedcut_quantity_left'),
        ('slaughter_house', '0005_remove_slaughterhouserecord_associated_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='part_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.inventorybreed'),
        ),
    ]
