# Generated by Django 4.2.7 on 2023-12-07 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0007_alter_slaughterhouserecord_sale_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slaughterhouserecord',
            old_name='sale_type',
            new_name='status',
        ),
    ]
