# Generated by Django 4.2.7 on 2023-12-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0040_alter_breedcut_quantity_left'),
        ('slaughter_house', '0007_alter_slaughterhouserecord_part_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='inventory_breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory_management.inventorybreed'),
        ),
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='part_name',
            field=models.CharField(choices=[('thighs', 'Thighs'), ('ribs', 'Ribs'), ('loin', 'Loin'), ('shoulder', 'Shoulder'), ('shanks', 'Shanks'), ('organ_meat', 'Organ Meat'), ('intestines', 'Intestines'), ('tripe', 'Tripe'), ('sweetbreads', 'Sweetbreads')], default='shank', max_length=255),
        ),
    ]
