# Generated by Django 4.2.7 on 2023-12-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0008_slaughterhouserecord_inventory_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='part_name',
            field=models.CharField(choices=[('thighs', 'Thighs'), ('ribs', 'Ribs'), ('loin', 'Loin'), ('shoulder', 'Shoulder'), ('shanks', 'Shanks'), ('organ_meat', 'Organ Meat'), ('intestines', 'Intestines'), ('tripe', 'Tripe'), ('sweetbreads', 'Sweetbreads')], default='Shank', max_length=255),
        ),
    ]
