# Generated by Django 4.2.7 on 2023-12-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0009_alter_slaughterhouserecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='sale_choice',
            field=models.CharField(choices=[('export_cuts', 'Export Cuts'), ('local_sale_cuts', 'Local Sale Cuts')], default='export_cuts', max_length=255),
        ),
    ]
