# Generated by Django 4.2.7 on 2023-12-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0010_slaughterhouserecord_sale_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaughterhouserecord',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
