# Generated by Django 4.2.7 on 2023-12-07 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0011_slaughterhouserecord_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slaughterhouserecord',
            old_name='total',
            new_name='total_quantity',
        ),
    ]
