# Generated by Django 4.2.7 on 2023-12-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0011_alter_slaughterhouserecord_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughterhouserecord',
            name='part_name',
            field=models.CharField(max_length=255),
        ),
    ]
