# Generated by Django 4.2.7 on 2023-12-07 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slaughter_house', '0012_rename_total_slaughterhouserecord_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slaughterhouserecord',
            name='total_quantity',
        ),
    ]
