# Generated by Django 5.0 on 2023-12-25 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0004_rename_breads_supplied_breadertrade_breeds_supplied'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
                ('other_details', models.TextField()),
                ('breeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.breader')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_code', models.CharField(max_length=3)),
                ('reference', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('breeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.breader')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.transaction')),
            ],
        ),
    ]
