# Generated by Django 5.0 on 2023-12-25 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentmethod_breeder_and_more'),
        ('transaction', '0005_breadertrade_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='breeder',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='breeder',
        ),
        migrations.CreateModel(
            name='EquityBankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payer_email', models.EmailField(max_length=254)),
                ('payment_description', models.TextField()),
                ('breeder_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.breadertrade')),
                ('payer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.abattoir')),
            ],
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
