# Generated by Django 5.0 on 2023-12-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_paymentmethod_breeder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equitybankpayment',
            name='payer_email',
        ),
        migrations.RemoveField(
            model_name='equitybankpayment',
            name='payment_description',
        ),
    ]
