# Generated by Django 5.0 on 2024-01-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0002_rename_username_buyer_buyer'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsstatus',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.buyer'),
        ),
    ]
