# Generated by Django 5.0.1 on 2024-02-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0009_alter_customuser_role'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=255, null=True)),
                ('package_description', models.CharField(blank=True, max_length=255, null=True)),
                ('package_charge', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('length', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='logisticsstatus',
            name='logistics_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logisticsstatus',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
        ),
        migrations.AddField(
            model_name='logisticsstatus',
            name='shipping_mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logisticsstatus',
            name='time_of_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logisticsstatus',
            name='package_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.packageinfo'),
        ),
    ]
