# Generated by Django 5.0 on 2024-01-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_logisticsstatus_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsstatus',
            name='is_status_updated',
            field=models.BooleanField(default=False),
        ),
    ]
