# Generated by Django 5.0.1 on 2024-02-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_packageinfo_logisticsstatus_logistics_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsstatus',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('dispatched', 'Dispatched'), ('shipped', 'Shipped'), ('arrived', 'Arrival'), ('received', 'Received')], default='ordered', max_length=255),
        ),
        migrations.AlterField(
            model_name='packageinfo',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packageinfo',
            name='length',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packageinfo',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
