# Generated by Django 5.0.1 on 2024-02-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_controlcenter_collateralmanager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlcenter',
            name='description',
        ),
        migrations.AddField(
            model_name='controlcenter',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='controlcenter',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
