# Generated by Django 5.0.1 on 2024-02-16 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_remove_controlcenter_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateralmanager',
            name='assigned_control_center',
        ),
        migrations.AddField(
            model_name='controlcenter',
            name='assigned_control_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.collateralmanager'),
        ),
    ]
