# Generated by Django 5.0.1 on 2024-02-16 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_remove_collateralmanager_assigned_control_center_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlcenter',
            old_name='assigned_control_center',
            new_name='assigned_collateral_agent',
        ),
    ]
