# Generated by Django 5.0.1 on 2024-02-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0010_alter_customuser_role'),
        ('logistics', '0007_rename_assigned_control_center_controlcenter_assigned_collateral_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateralmanager',
            name='associated_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
        ),
    ]
