# Generated by Django 5.0.1 on 2024-02-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_collateralmanager_associated_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collateralmanager',
            name='associated_seller',
        ),
    ]
