# Generated by Django 5.0.1 on 2024-02-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0011_alter_customuser_role'),
        ('logistics', '0009_remove_collateralmanager_associated_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateralmanager',
            name='associated_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
        ),
    ]
