# Generated by Django 5.0.1 on 2024-02-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_collateralmanager_associated_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlcenter',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='controlcenter',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
