# Generated by Django 5.0.1 on 2024-02-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_controlcenter_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticsstatus',
            name='time_of_delivery',
        ),
    ]
