# Generated by Django 5.0.1 on 2024-02-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_remove_logisticsstatus_time_of_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticsstatus',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='logisticsstatus',
            name='seller',
        ),
    ]
