# Generated by Django 5.0.1 on 2024-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_logisticsstatus_buyer_logisticsstatus_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticsstatus',
            name='bill_of_lading',
            field=models.FileField(blank=True, null=True, upload_to='bill_of_landings'),
        ),
    ]
