# Generated by Django 5.0.1 on 2024-02-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_logisticsstatus_bill_of_lading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticsstatus',
            name='bill_of_lading',
        ),
        migrations.AddField(
            model_name='packageinfo',
            name='bill_of_lading',
            field=models.FileField(blank=True, null=True, upload_to='bill_of_landings'),
        ),
    ]
