# Generated by Django 5.0.1 on 2024-02-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_remove_logisticsstatus_bill_of_lading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collateralmanager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
