# Generated by Django 5.0.1 on 2024-03-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0011_alter_customuser_role'),
        ('logistics', '0018_controlcenter_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcenter',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
        ),
    ]
