# Generated by Django 5.0.1 on 2024-03-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_controlcenter_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlcenter',
            name='total_breed_supply',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
