# Generated by Django 5.0.1 on 2024-03-04 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0021_controlcenter_total_breed_supply_non_negative'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='controlcenter',
            name='total_breed_supply_non_negative',
        ),
        migrations.RemoveField(
            model_name='controlcenter',
            name='total_breed_supply',
        ),
    ]
