# Generated by Django 5.0 on 2023-12-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybreedsales',
            name='status',
            field=models.CharField(choices=[('in_the warehouse', 'In The Warehouse'), ('slaughtered', 'Slaughtered'), ('sold', 'Sold')], default='in_the_warehouse', max_length=255),
        ),
    ]
