# Generated by Django 4.2.7 on 2023-12-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorybreed',
            old_name='quantity',
            new_name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='inventorybreed',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventorybreed',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventorybreed',
            name='status',
        ),
        migrations.RemoveField(
            model_name='inventorybreed',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='inventorybreed',
            name='breed',
            field=models.CharField(choices=[('goats', 'Goats'), ('sheep', 'Sheep'), ('cows', 'Cows'), ('pigs', 'Pigs')], default='goats', max_length=255),
        ),
    ]
