# Generated by Django 4.2.7 on 2023-12-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_yard', 'In Yard'), ('slaughtered', 'Slaughtered'), ('sold', 'Sold')], default='in_yard', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBreedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_date', models.DateField()),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.inventorybreed')),
            ],
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
