# Generated by Django 5.0.1 on 2024-02-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedcut',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inventorybreedsales',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
