# Generated by Django 4.2.7 on 2023-12-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_inventorybreed_inventorybreedtransaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorybreedtransaction',
            old_name='goat',
            new_name='breed',
        ),
    ]
