# Generated by Django 5.0.1 on 2024-02-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_breedcut_weight_inventorybreedsales_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedcut',
            name='breed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breedcut',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breedcut',
            name='sale_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
