# Generated by Django 5.0 on 2023-12-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_inventorybreedsales_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybreedsales',
            name='breed',
            field=models.CharField(choices=[('goats', 'Goats'), ('sheep', 'Sheep'), ('cows', 'Cows'), ('pigs', 'Pigs')], default='goats', max_length=255),
        ),
    ]
