# Generated by Django 5.0 on 2023-12-10 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_alter_inventorybreedsales_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybreedsales',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.breedcut'),
        ),
    ]
