# Generated by Django 5.0.1 on 2024-02-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_alter_breedcut_breed_alter_breedcut_part_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybreed',
            name='breed',
            field=models.CharField(blank=True, default='goats', max_length=255, null=True),
        ),
    ]
