# Generated by Django 4.2.7 on 2023-12-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_rename_goat_inventorybreedtransaction_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybreedtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('export_cuts', 'Export Cuts'), ('other_parts', 'Other Parts')], max_length=255),
        ),
    ]
