# Generated by Django 4.2.7 on 2023-12-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_alter_inventorybreedtransaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='inventorybreed',
            old_name='part',
            new_name='name',
        ),
        migrations.AddField(
            model_name='inventorybreed',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventorybreed',
            name='status',
            field=models.CharField(choices=[('in_yard', 'In Yard'), ('slaughtered', 'Slaughtered'), ('sold', 'Sold')], max_length=20),
        ),
        migrations.AddField(
            model_name='inventorybreed',
            name='parts',
            field=models.ManyToManyField(to='inventory_management.breedpart'),
        ),
    ]
