# Generated by Django 4.2.7 on 2023-12-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_breedpart_rename_part_inventorybreed_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybreed',
            name='status',
            field=models.CharField(choices=[('in_yard', 'In Yard'), ('sold', 'Sold'), ('slaughtered', 'Slaughtered')], max_length=20),
        ),
    ]
