# Generated by Django 4.2.7 on 2023-12-05 18:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_management', '0008_alter_inventorybreedtransaction_transaction_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryBreedTransaction',
            new_name='InventoryBreedSales',
        ),
        migrations.RenameField(
            model_name='inventorybreedsales',
            old_name='transaction_date',
            new_name='sale_date',
        ),
        migrations.RenameField(
            model_name='inventorybreedsales',
            old_name='transaction_type',
            new_name='sale_type',
        ),
    ]
