# Generated by Django 4.2.7 on 2023-12-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0009_rename_inventorybreedtransaction_inventorybreedsales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorybreed',
            name='parts',
        ),
        migrations.AddField(
            model_name='breedpart',
            name='inventory_breed',
            field=models.ManyToManyField(max_length=255, to='inventory_management.inventorybreed'),
        ),
        migrations.AlterField(
            model_name='inventorybreed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventorybreed',
            name='status',
            field=models.CharField(choices=[('in_yard', 'In Yard'), ('slaughtered', 'Slaughtered'), ('sold', 'Sold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorybreedsales',
            name='sale_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
