# Generated by Django 4.2.7 on 2023-12-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0010_remove_inventorybreed_parts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybreedsales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
