# Generated by Django 4.2.7 on 2023-12-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0012_inventorybreedsales_part_name_delete_breedpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybreed',
            name='status',
            field=models.CharField(choices=[('added', 'Added'), ('in_yard', 'In Yard'), ('slaughtered', 'Slaughtered'), ('sold', 'Sold')], max_length=20),
        ),
    ]
