# Generated by Django 4.2.7 on 2023-12-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0013_alter_inventorybreed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybreed',
            name='original_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
