# Generated by Django 4.2.7 on 2023-12-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0015_remove_inventorybreed_original_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybreed',
            name='status',
            field=models.CharField(choices=[('in_yard', 'In Yard'), ('slaughtered', 'Slaughtered'), ('sold', 'Sold')], max_length=20),
        ),
    ]
