# Generated by Django 4.2.7 on 2023-12-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_alter_breadertrade_options'),
        ('inventory_management', '0019_alter_inventorybreed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorybreed',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventorybreed',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventorybreed',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='inventorybreed',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.breadertrade'),
        ),
    ]
