# Generated by Django 4.2.7 on 2023-12-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0020_remove_inventorybreed_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorybreed',
            name='quantity',
        ),
    ]
