# Generated by Django 4.2.7 on 2023-12-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0021_remove_inventorybreed_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorybreed',
            name='name',
        ),
    ]
