# Generated by Django 4.2.7 on 2023-12-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0024_inventory_partssales_slaughteredparts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('in_yard', 'In Yard'), ('slaughtered', 'Slaughtered')], default='in_yard', max_length=20),
        ),
        migrations.AlterField(
            model_name='slaughteredparts',
            name='inventory_status',
            field=models.CharField(choices=[('in_warehouse', 'In Warehouse'), ('sold', 'Sold')], default='in_warehouse', max_length=20),
        ),
    ]
