# Generated by Django 4.2.7 on 2023-12-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0027_alter_inventorybreed_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybreed',
            name='breed_name',
            field=models.CharField(choices=[('goats', 'Goats'), ('sheep', 'Sheep'), ('cows', 'Cows'), ('pigs', 'Pigs')], default='goats', max_length=255, null=True, unique=True),
        ),
    ]
