# Generated by Django 4.2.7 on 2023-12-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0028_alter_inventorybreed_breed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorybreed',
            name='created_by',
        ),
    ]
