# Generated by Django 4.2.7 on 2023-12-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0030_inventorybreed_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybreedsales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
