# Generated by Django 4.2.7 on 2023-12-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0031_alter_inventorybreedsales_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybreedsales',
            name='part_name',
            field=models.CharField(choices=[('thighs', 'Thighs'), ('ribs', 'Ribs'), ('loin', 'Loin'), ('shoulder', 'Shoulder'), ('shanks', 'Shanks'), ('organ_meat', 'Organ Meat'), ('intestines', 'Intestines'), ('tripe', 'Tripe'), ('sweetbreads', 'Sweetbreads')], default='shanks', max_length=255),
        ),
    ]
