# Generated by Django 4.2.7 on 2023-12-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0034_alter_inventorybreed_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedCut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(choices=[('thighs', 'Thighs'), ('ribs', 'Ribs'), ('loin', 'Loin'), ('shoulder', 'Shoulder'), ('shanks', 'Shanks'), ('organ_meat', 'Organ Meat'), ('intestines', 'Intestines'), ('tripe', 'Tripe'), ('sweetbreads', 'Sweetbreads')], max_length=255)),
                ('sale_type', models.CharField(choices=[('export_cuts', 'Export Cuts'), ('local_sales_cuts', 'Local Sales Cuts')], max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_management.inventorybreed')),
            ],
        ),
    ]
