# Generated by Django 4.2.7 on 2023-12-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0035_breedcut'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedcut',
            name='status',
            field=models.CharField(choices=[('in_warehouse', 'In the Warehouse'), ('sold', 'Sold')], default='in_warehouse', max_length=20),
        ),
    ]
