# Generated by Django 4.2.7 on 2023-12-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0036_breedcut_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='breedcut',
            name='quantity_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
