# Generated by Django 4.2.7 on 2023-12-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0038_alter_breedcut_quantity_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedcut',
            name='quantity_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
