# Generated by Django 4.2.7 on 2023-12-07 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abattoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Breader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BreaderTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('breed', models.CharField(choices=[('goats', 'Goats'), ('sheep', 'Sheep'), ('cows', 'Cows'), ('pigs', 'Pigs')], default='goats', max_length=255)),
                ('breads_supplied', models.PositiveIntegerField(default=0)),
                ('goat_weight', models.PositiveIntegerField(default=0)),
                ('community', models.CharField(default='Example ABC Community', max_length=255)),
                ('market', models.CharField(default='ABC Market', max_length=255)),
                ('head_of_family', models.CharField(default='Example ABC Family', max_length=255)),
                ('vaccinated', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('abattoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.abattoir')),
                ('breader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.breader')),
            ],
        ),
        migrations.CreateModel(
            name='AbattoirPaymentToBreader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('breader_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.breadertrade')),
            ],
        ),
    ]
