# Generated by Django 5.0 on 2023-12-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadertrade',
            name='breeder',
        ),
    ]
