# Generated by Django 5.0 on 2024-01-04 22:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='bank_account_number',
            field=models.CharField(default=1234567891011, max_length=30),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
