# Generated by Django 4.2.7 on 2023-11-26 06:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Breader',
        ),
        migrations.RenameModel(
            old_name='Payment',
            new_name='BreaderPayment',
        ),
        migrations.RenameModel(
            old_name='SupplyTransaction',
            new_name='BreaderTransaction',
        ),
    ]
