# Generated by Django 5.0 on 2024-01-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abattoirpaymenttobreader',
            name='amount',
        ),
    ]
