# Generated by Django 4.2.7 on 2023-12-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='total_quantity_supplied',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
