# Generated by Django 5.0 on 2024-01-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_breadertrade_bank_account_number_breadertrade_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadertrade',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
