# Generated by Django 5.0 on 2024-01-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_abattoirpaymenttobreader_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abattoirpaymenttobreader',
            name='status',
        ),
    ]
