# Generated by Django 5.0 on 2023-12-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_breadertrade_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadertrade',
            name='transaction_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
