# Generated by Django 5.0 on 2023-12-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_breadertrade_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadertrade',
            name='reference',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
    ]
