# Generated by Django 5.0.1 on 2024-02-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_breadertrade_breeder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadertrade',
            name='breed',
            field=models.CharField(max_length=255),
        ),
    ]
