# Generated by Django 5.0 on 2023-12-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_breadertrade_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadertrade',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
