# Generated by Django 5.0 on 2023-12-18 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_breadertrade_breeder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breadertrade',
            old_name='breads_supplied',
            new_name='breeds_supplied',
        ),
    ]
