# Generated by Django 4.2.7 on 2023-11-26 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_supplier_breadertransaction_breader_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breaderpayment',
            old_name='supplier',
            new_name='breader',
        ),
    ]
