# Generated by Django 4.2.7 on 2023-12-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_breadertrade_total_quantity_supplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='update_total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
