# Generated by Django 5.0 on 2024-01-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_breadertrade_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='id_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
