# Generated by Django 5.0.1 on 2024-02-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_breadertrade_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='abattoir',
            name='breeders',
            field=models.ManyToManyField(blank=True, related_name='abattoirs_registered', to='transaction.breader'),
        ),
    ]
