# Generated by Django 4.2.7 on 2023-11-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_rename_supplier_breaderpayment_breader'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbattoirPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('abattoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.abattoir')),
            ],
        ),
        migrations.RenameModel(
            old_name='BreaderTransaction',
            new_name='BreaderTrade',
        ),
        migrations.DeleteModel(
            name='BreaderPayment',
        ),
        migrations.AddField(
            model_name='abattoirpayment',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.breadertrade'),
        ),
    ]
