# Generated by Django 5.0 on 2023-12-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_rename_breads_supplied_breadertrade_breeds_supplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
