# Generated by Django 4.2.7 on 2023-12-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_breadertrade_update_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadertrade',
            name='update_total_quantity',
        ),
    ]
