# Generated by Django 5.0 on 2023-12-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_breadertrade_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='bank_account_number',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
