# Generated by Django 5.0.1 on 2024-02-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_abattoir_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='tag_number',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
