# Generated by Django 5.0 on 2023-12-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_breadertrade_bank_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadertrade',
            name='transaction_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
