# Generated by Django 4.2.7 on 2023-12-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_breadertrade_community_breadertrade_goat_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='animal_name',
            field=models.CharField(default='eg goats, cows... etc', max_length=255),
        ),
    ]
