# Generated by Django 5.0.1 on 2024-02-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_breadertrade_tag_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadertrade',
            name='tag_number',
        ),
    ]
