# Generated by Django 4.2.7 on 2023-12-03 11:29

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_breadertrade_animal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbattoirPaymentToBreader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='AbattoirPayment',
        ),
        migrations.AddField(
            model_name='abattoirpaymenttobreader',
            name='breader_trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.breadertrade'),
        ),
    ]
