# Generated by Django 4.2.7 on 2023-12-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_abattoirpaymenttobreader_breadertrade_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadertrade',
            name='animal_name',
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='breed_name',
            field=models.CharField(choices=[('goats', 'Goats'), ('sheep', 'Sheep'), ('cows', 'Cows'), ('pigs', 'Pigs')], default='Goats', max_length=255),
        ),
    ]
