# Generated by Django 4.2.7 on 2023-12-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_remove_breadertrade_animal_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breadertrade',
            options={'ordering': ['-transaction_date']},
        ),
    ]
