# Generated by Django 5.0.1 on 2024-02-23 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0011_alter_customuser_role'),
        ('transaction', '0009_rename_user_breader_breeder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abattoir',
            name='breeders',
            field=models.ManyToManyField(blank=True, related_name='abattoirs_registered', to='custom_registration.seller'),
        ),
        migrations.AlterField(
            model_name='breadertrade',
            name='abattoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
        ),
    ]
