# Generated by Django 5.0.1 on 2024-02-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0011_alter_customuser_role'),
        ('transaction', '0010_alter_abattoir_breeders_alter_breadertrade_abattoir'),
    ]

    operations = [
        migrations.AddField(
            model_name='breader',
            name='seller',
            field=models.ManyToManyField(to='custom_registration.seller'),
        ),
    ]
