# Generated by Django 5.0.1 on 2024-02-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0011_alter_customuser_role'),
        ('transaction', '0011_breader_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breader',
            name='seller',
        ),
        migrations.AddField(
            model_name='breader',
            name='sellers',
            field=models.ManyToManyField(blank=True, related_name='sellers_registered', to='custom_registration.seller'),
        ),
    ]
