# Generated by Django 4.2.7 on 2023-12-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_alter_breadertrade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breadertrade',
            options={'ordering': ['-transaction_date']},
        ),
        migrations.AlterField(
            model_name='breadertrade',
            name='animal_name',
            field=models.CharField(choices=[('goats', 'Goats'), ('sheep', 'Sheep'), ('cows', 'Cows'), ('pigs', 'Pigs')], default='Goats', max_length=255),
        ),
    ]
