# Generated by Django 5.0.1 on 2024-02-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_remove_breader_seller_breader_sellers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breader',
            old_name='sellers',
            new_name='seller',
        ),
    ]
