# Generated by Django 4.2.7 on 2023-12-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_alter_breadertrade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breadertrade',
            options={},
        ),
        migrations.AlterField(
            model_name='breadertrade',
            name='animal_name',
            field=models.CharField(default='eg goats, cows... etc', max_length=255),
        ),
    ]
