# Generated by Django 5.0.1 on 2024-02-23 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0011_alter_customuser_role'),
        ('transaction', '0013_rename_sellers_breader_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breader',
            name='seller',
        ),
        migrations.AddField(
            model_name='breader',
            name='seller',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
            preserve_default=False,
        ),
    ]
