# Generated by Django 5.0.1 on 2024-02-23 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_remove_breader_seller_breader_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breader',
            name='seller',
        ),
        migrations.AlterField(
            model_name='abattoir',
            name='breeders',
            field=models.ManyToManyField(blank=True, related_name='abattoirs_registered', to='transaction.breader'),
        ),
        migrations.AlterField(
            model_name='breadertrade',
            name='abattoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.abattoir'),
        ),
    ]
