# Generated by Django 4.2.7 on 2023-12-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_rename_breed_name_breadertrade_animal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breadertrade',
            old_name='animal_name',
            new_name='breed_name',
        ),
    ]
