# Generated by Django 5.0.1 on 2024-02-23 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0011_alter_customuser_role'),
        ('transaction', '0015_remove_breader_seller_alter_abattoir_breeders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breadertrade',
            name='abattoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
        ),
    ]
