# Generated by Django 5.0.1 on 2024-02-23 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0011_alter_customuser_role'),
        ('transaction', '0016_alter_breadertrade_abattoir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadertrade',
            name='abattoir',
        ),
        migrations.AddField(
            model_name='breader',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
        ),
    ]
