# Generated by Django 4.2.7 on 2023-12-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0016_rename_animal_name_breadertrade_breed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadertrade',
            name='user',
        ),
    ]
