# Generated by Django 5.0.1 on 2024-02-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0017_remove_breadertrade_abattoir_breader_seller_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breader',
            old_name='breeder',
            new_name='user',
        ),
    ]
