# Generated by Django 5.0.1 on 2024-02-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_rename_breeder_breader_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breader',
            old_name='user',
            new_name='breeder',
        ),
    ]
