# Generated by Django 5.0.1 on 2024-02-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0019_rename_user_breader_breeder'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='control_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
