# Generated by Django 5.0.1 on 2024-02-29 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_controlcenter_created_at'),
        ('transaction', '0021_remove_breadertrade_control_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='control_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.controlcenter'),
        ),
    ]
