# Generated by Django 5.0.1 on 2024-02-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0024_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='total',
        ),
    ]
