# Generated by Django 5.0.1 on 2024-02-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0026_inventory_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='trade',
        ),
        migrations.AddField(
            model_name='inventory',
            name='trade',
            field=models.ManyToManyField(blank=True, null=True, to='transaction.breadertrade'),
        ),
    ]
