# Generated by Django 5.0.1 on 2024-03-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_controlcenter_seller'),
        ('transaction', '0027_remove_inventory_trade_inventory_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadertrade',
            name='control_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.controlcenter'),
        ),
    ]
