# Generated by Django 5.0.1 on 2024-03-05 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_controlcenter_created_at'),
        ('transaction', '0027_remove_inventory_trade_inventory_trade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breader',
            name='seller',
        ),
        migrations.AddField(
            model_name='breadertrade',
            name='control_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.controlcenter'),
        ),
        migrations.AlterField(
            model_name='breadertrade',
            name='breeder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
