# Generated by Django 5.0.1 on 2024-03-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0028_breadertrade_control_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breader',
            name='seller',
        ),
    ]
