# Generated by Django 5.0.1 on 2024-02-06 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('is_complete', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('breader_trade', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.breadertrade')),
            ],
        ),
    ]
