# Generated by Django 4.2.7 on 2023-12-03 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0007_breadertrade_animal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('is_complete', models.BooleanField(default=False)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('breader_trade', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.breadertrade')),
            ],
        ),
    ]
