# Generated by Django 5.0.1 on 2024-02-06 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('buyer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('buyer_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_country', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(choices=[('chevon', 'Chevon (Goat Meat)'), ('mutton', 'Mutton'), ('beef', 'Beef'), ('pork', 'Pork')], default='chevon', max_length=255)),
                ('part_name', models.CharField(choices=[('ribs', 'Ribs'), ('thighs', 'Thighs'), ('loin', 'Loin'), ('shoulder', 'Shoulder'), ('shanks', 'Shanks'), ('organ_meat', 'Organ Meat'), ('intestines', 'Intestines'), ('tripe', 'Tripe'), ('sweetbreads', 'Sweetbreads')], default='ribs', max_length=255)),
                ('sale_type', models.CharField(choices=[('export_cut', 'Export Cut'), ('local_cut', 'Local Cut')], default='export_cut', max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, editable=False, null=True)),
                ('attached_lc_document', models.FileField(upload_to='invoice_documents/')),
                ('invoice_number', models.SlugField(editable=False, unique=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='LetterOfCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='received', max_length=255)),
                ('lc_document', models.FileField(blank=True, null=True, upload_to='lc_documents/')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.buyer')),
            ],
        ),
    ]
