# Generated by Django 5.0.1 on 2024-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_address', models.TextField()),
                ('buyer_contact', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_address', models.TextField()),
                ('seller_contact', models.CharField(max_length=100)),
                ('shipping_address', models.TextField()),
                ('product_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_terms', models.CharField(max_length=255)),
                ('delivery_terms', models.CharField(max_length=255)),
                ('reference_numbers', models.CharField(max_length=255)),
                ('special_instructions', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('authorized_signature', models.CharField(max_length=255)),
                ('signature_date', models.DateField()),
                ('tracking_information', models.TextField()),
                ('record_keeping', models.TextField()),
            ],
        ),
    ]
