# Generated by Django 5.0.1 on 2024-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0002_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfCreditSellerToTrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('beneficiary_address', models.TextField()),
                ('issuing_bank_name', models.CharField(max_length=255)),
                ('issuing_bank_address', models.TextField()),
                ('advising_bank_name', models.CharField(max_length=255)),
                ('advising_bank_address', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('shipment_period', models.CharField(max_length=100)),
                ('documents_required', models.TextField()),
                ('special_conditions', models.TextField()),
                ('payment_at_sight', models.BooleanField(default=False)),
                ('deferred_payment', models.BooleanField(default=False)),
                ('payment_terms', models.CharField(max_length=255)),
                ('reference_numbers', models.CharField(max_length=255)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('authorized_signature_issuing_bank', models.CharField(max_length=255)),
                ('authorized_signature_advising_bank', models.CharField(max_length=255)),
                ('signature_date', models.DateField()),
                ('tracking_information', models.TextField()),
                ('record_keeping', models.TextField()),
            ],
        ),
    ]
