# Generated by Django 5.0 on 2023-12-18 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0002_alter_buyer_options_alter_buyer_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.buyer'),
        ),
    ]
