# Generated by Django 5.0 on 2024-01-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0003_alter_purchaseorder_buyer_alter_purchaseorder_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
