# Generated by Django 5.0 on 2023-12-18 07:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0003_alter_invoice_buyer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='banking_transactions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bill_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='cataloging_live_deals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='flash_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='management_of_deals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_issuance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ship_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ship_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='tracking_financed_paid_off_deals',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='breed',
            field=models.CharField(choices=[('chevon', 'Chevon (Goat Meat)'), ('mutton', 'Mutton'), ('beef', 'Beef'), ('pork', 'Pork')], default='chevon', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='part_name',
            field=models.CharField(choices=[('ribs', 'Ribs'), ('loin', 'Loin')], default='ribs', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sale_type',
            field=models.CharField(choices=[('export_cut', 'Export Cut'), ('local_cut', 'Local Cut')], default='export_cut', max_length=255),
        ),
    ]
