# Generated by Django 5.0 on 2023-12-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0003_alter_invoice_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='user',
            new_name='username',
        ),
    ]
