# Generated by Django 5.0.1 on 2024-02-06 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0002_initial'),
        ('invoice_generator', '0003_letterofcreditsellertotrader'),
        ('transaction', '0005_abattoir_breeders'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofcreditsellertotrader',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.bank'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letterofcreditsellertotrader',
            name='breeder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.breader'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letterofcreditsellertotrader',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.abattoir'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.abattoir'),
            preserve_default=False,
        ),
    ]
