# Generated by Django 5.0 on 2023-12-18 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0004_invoice_banking_transactions_invoice_bill_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.buyer'),
        ),
    ]
