# Generated by Django 5.0.1 on 2024-02-06 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0004_letterofcreditsellertotrader_bank_and_more'),
        ('transaction', '0005_abattoir_breeders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterofcreditsellertotrader',
            name='record_keeping',
        ),
        migrations.RemoveField(
            model_name='letterofcreditsellertotrader',
            name='tracking_information',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='buyer_name',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='trader_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.breader'),
            preserve_default=False,
        ),
    ]
