# Generated by Django 5.0 on 2023-12-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0005_alter_invoice_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='banking_transactions',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='cataloging_live_deals',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='flash_message',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='management_of_deals',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='purchase_issuance',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tracking_financed_paid_off_deals',
        ),
    ]
