# Generated by Django 5.0 on 2023-12-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0005_alter_invoice_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='part_name',
            field=models.CharField(choices=[('ribs', 'Ribs'), ('thighs', 'Thighs'), ('loin', 'Loin'), ('shoulder', 'Shoulder'), ('shanks', 'Shanks'), ('organ_meat', 'Organ Meat'), ('intestines', 'Intestines'), ('tripe', 'Tripe'), ('sweetbreads', 'Sweetbreads')], default='ribs', max_length=255),
        ),
    ]
