# Generated by Django 5.0 on 2024-01-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0005_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='_original_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
