# Generated by Django 5.0.1 on 2024-02-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0005_remove_letterofcreditsellertotrader_record_keeping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='record_keeping',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='seller_name',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tracking_information',
        ),
    ]
