# Generated by Django 5.0 on 2024-01-19 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0006_purchaseorder__original_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='items',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='items',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='buyer',
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_country',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_email',
            field=models.EmailField(blank=True, editable=False, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_first_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_last_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='buyer_phone',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='breed',
            field=models.CharField(choices=[('chevon', 'Chevon (Goat Meat)'), ('mutton', 'Mutton'), ('beef', 'Beef'), ('pork', 'Pork')], default='chevon', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_document',
            field=models.FileField(blank=True, null=True, upload_to='invoice_documents/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='part_name',
            field=models.CharField(choices=[('ribs', 'Ribs'), ('thighs', 'Thighs'), ('loin', 'Loin'), ('shoulder', 'Shoulder'), ('shanks', 'Shanks'), ('organ_meat', 'Organ Meat'), ('intestines', 'Intestines'), ('tripe', 'Tripe'), ('sweetbreads', 'Sweetbreads')], default='ribs', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='sale_type',
            field=models.CharField(choices=[('export_cut', 'Export Cut'), ('local_cut', 'Local Cut')], default='export_cut', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.CreateModel(
            name='LetterOfCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=255)),
                ('lc_document', models.FileField(blank=True, null=True, upload_to='lc_documents/')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
