# Generated by Django 5.0.1 on 2024-02-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0006_remove_purchaseorder_record_keeping_and_more'),
        ('transaction', '0005_abattoir_breeders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofcreditsellertotrader',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='lc_from_local_seller_to_local_trader/'),
        ),
        migrations.AlterField(
            model_name='letterofcreditsellertotrader',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='letterofcreditsellertotrader',
            name='signature_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='signature_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ProformaInvoiceFromTraderToSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('buyer_address', models.TextField()),
                ('seller_address', models.TextField()),
                ('product_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_terms', models.CharField(max_length=255)),
                ('delivery_terms', models.CharField(max_length=255)),
                ('reference_numbers', models.CharField(max_length=255)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='invoices_from_local_traders_to_local_sellers/')),
                ('authorized_signature_buyer', models.CharField(max_length=255)),
                ('authorized_signature_seller', models.CharField(max_length=255)),
                ('signature_date', models.DateField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.abattoir')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.breader')),
            ],
        ),
    ]
