# Generated by Django 5.0 on 2023-12-18 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0006_remove_invoice_banking_transactions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bill_to',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ship_to',
        ),
    ]
