# Generated by Django 5.0 on 2024-01-19 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0007_remove_item_product_remove_invoice_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_document',
            new_name='attached_lc_document',
        ),
    ]
