# Generated by Django 5.0 on 2023-12-18 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0007_remove_invoice_bill_to_remove_invoice_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invoice_generator.buyer'),
            preserve_default=False,
        ),
    ]
