# Generated by Django 5.0.1 on 2024-02-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0007_alter_letterofcreditsellertotrader_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofcreditsellertotrader',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='letterofcreditsellertotrader',
            name='payment_type',
            field=models.CharField(choices=[('at_sight', 'Payment at Sight'), ('deferred_payment', 'Deferred Payment')], default='at_sight', max_length=20),
        ),
        migrations.AddField(
            model_name='letterofcreditsellertotrader',
            name='reference_type',
            field=models.CharField(choices=[('order_number', 'Order Number'), ('contract_number', 'Contract Number'), ('other', 'Other')], default='order_number', max_length=20),
        ),
        migrations.AddField(
            model_name='letterofcreditsellertotrader',
            name='tracking_status',
            field=models.CharField(choices=[('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('delayed', 'Delayed')], default='in_transit', max_length=20),
        ),
    ]
