# Generated by Django 5.0.1 on 2024-02-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0008_letterofcreditsellertotrader_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
