# Generated by Django 5.0 on 2024-01-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0008_rename_invoice_document_invoice_attached_lc_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofcredit',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
