# Generated by Django 5.0.1 on 2024-02-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0009_purchaseorder_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total_price',
        ),
    ]
