# Generated by Django 5.0.1 on 2024-02-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0010_remove_purchaseorder_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_country',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_first_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_last_name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='buyer_phone',
        ),
    ]
