# Generated by Django 5.0.1 on 2024-02-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0012_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='seller_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
