# Generated by Django 5.0.1 on 2024-02-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0013_quotation_seller_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='seller_address',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='seller_company',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='seller_country',
        ),
        migrations.AddField(
            model_name='quotation',
            name='coonfirm',
            field=models.BooleanField(default=False),
        ),
    ]
