# Generated by Django 5.0.1 on 2024-02-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0014_remove_quotation_seller_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='coonfirm',
            new_name='confirm',
        ),
    ]
