# Generated by Django 5.0.1 on 2024-02-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0016_buyer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterofcreditsellertotrader',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='letterofcreditsellertotrader',
            name='reference_type',
        ),
        migrations.RemoveField(
            model_name='proformainvoicefromtradertoseller',
            name='authorized_signature_buyer',
        ),
        migrations.RemoveField(
            model_name='proformainvoicefromtradertoseller',
            name='authorized_signature_seller',
        ),
        migrations.RemoveField(
            model_name='proformainvoicefromtradertoseller',
            name='signature_date',
        ),
    ]
