# Generated by Django 5.0.1 on 2024-02-10 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0008_seller_created_at'),
        ('invoice_generator', '0017_remove_letterofcreditsellertotrader_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
        ),
    ]
