# Generated by Django 5.0.1 on 2024-02-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0018_quotation_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='delivery_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
