# Generated by Django 5.0.1 on 2024-02-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0019_quotation_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='confirm',
            field=models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject'), ('review', 'Review')], max_length=255, null=True),
        ),
    ]
