# Generated by Django 5.0.1 on 2024-02-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0020_alter_quotation_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
