# Generated by Django 5.0.1 on 2024-02-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0021_alter_quotation_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='confirm',
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('review', 'Under Review')], default='review', max_length=20),
        ),
    ]
