# Generated by Django 5.0.1 on 2024-02-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0022_remove_quotation_confirm_quotation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='status',
            new_name='confirm',
        ),
    ]
