# Generated by Django 5.0.1 on 2024-02-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0023_rename_status_quotation_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='authorized_signature',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='buyer_address',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='buyer_contact',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='reference_numbers',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='seller_address',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='seller_contact',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='signature_date',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
