# Generated by Django 5.0.1 on 2024-02-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0024_rename_total_amount_purchaseorder_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='breed',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='part_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sale_type',
            field=models.CharField(max_length=255),
        ),
    ]
