# Generated by Django 5.0.1 on 2024-02-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0025_alter_invoice_breed_alter_invoice_part_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='attached_lc_document',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sale_type',
        ),
    ]
