# Generated by Django 5.0.1 on 2024-02-21 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0026_remove_invoice_attached_lc_document_and_more'),
        ('transaction', '0009_rename_user_breader_breeder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.abattoir'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='trader_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.breader'),
        ),
    ]
