# Generated by Django 5.0.1 on 2024-02-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0028_documenttoseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttoseller',
            name='file',
        ),
        migrations.AddField(
            model_name='documenttoseller',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
