# Generated by Django 5.0.1 on 2024-02-23 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0011_alter_customuser_role'),
        ('invoice_generator', '0030_alter_quotation_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='seller',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_registration.seller'),
        ),
    ]
