# Generated by Django 5.0.1 on 2024-02-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0040_invoice_buyer_invoice_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterofcredit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent_to_bank', 'Sent to bank'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='sent_to_bank', max_length=255),
        ),
    ]
