# Generated by Django 5.0.1 on 2024-02-29 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0043_letterofcredit_seller_alter_letterofcredit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='letterofcredit',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters_of_credit', to='invoice_generator.quotation'),
        ),
    ]
