# Generated by Django 5.0.1 on 2024-02-29 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0045_remove_letterofcredit_quotation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='letter_of_credit',
        ),
        migrations.AddField(
            model_name='letterofcredit',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_of_credit', to='invoice_generator.quotation'),
        ),
    ]
