# Generated by Django 5.0.1 on 2024-02-29 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0046_remove_quotation_letter_of_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='market',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='letterofcredit',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letters_of_credit', to='invoice_generator.quotation'),
        ),
    ]
