# Generated by Django 5.0.1 on 2024-02-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_generator', '0047_quotation_market_alter_letterofcredit_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letterofcreditsellertotrader',
            name='breeder',
        ),
        migrations.RemoveField(
            model_name='letterofcreditsellertotrader',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='proformainvoicefromtradertoseller',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='proformainvoicefromtradertoseller',
            name='trader',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='trader_name',
        ),
    ]
