# Generated by Django 5.0 on 2024-01-03 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=50)),
                ('bank_code', models.CharField(max_length=50, unique=True)),
                ('bank_abbreviation', models.CharField(max_length=50)),
                ('swift_code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('is_dormant', models.BooleanField()),
                ('status_title', models.CharField(max_length=100)),
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField()),
                ('status_narration', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('bank_branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_branch_name', models.CharField(max_length=100)),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('head_office', models.CharField(max_length=100)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_registration.bank')),
            ],
        ),
    ]
