# Generated by Django 5.0 on 2024-01-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerservice',
            name='transaction_reference',
        ),
        migrations.RemoveField(
            model_name='customerservice',
            name='transaction_type',
        ),
    ]
