# Generated by Django 5.0 on 2024-01-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0002_bank_status_bankbranch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payments_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_code', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('payment_initiation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent_to_bank', 'Sent to Bank for Payment Process'), ('disbursed', 'Disbursed'), ('paid', 'Paid')], default='sent_to_bank', max_length=100)),
            ],
        ),
    ]
