# Generated by Django 5.0 on 2024-01-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0003_payment'),
        ('transaction', '0006_breadertrade_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='breeder_trade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transaction.breadertrade'),
            preserve_default=False,
        ),
    ]
