# Generated by Django 5.0.1 on 2024-02-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0006_customuser_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
