# Generated by Django 5.0.1 on 2024-03-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_registration', '0011_alter_customuser_role'),
        ('transaction', '0029_remove_breader_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='breeders',
            field=models.ManyToManyField(to='transaction.breader'),
        ),
    ]
